parserOptions:
  ecmaVersion: 2018

env:
  es6: true
  node: true
  jest: true

extends:
  - 'htmlacademy/node'
  - 'plugin:prettier/recommended'

plugins:
  - 'prettier'
rules:
  object-curly-spacing: ["error", "never"]



