parserOptions:
  ecmaVersion: 2018

env:
  es6: true
  node: true
  jest: true

extends:
  - 'htmlacademy/node'
  - 'prettier'

plugins:
  - 'prettier'

rules:
  prettier/prettier: error
  newline-after-var: 1
  newline-before-return: 1
  object-curly-spacing: error
